apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-nfs-client-provisioner
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: redis-nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis-nfs-client-provisioner
    spec:
      imagePullSecrets:
      - name: harborsecret
      serviceAccount: redis-nfs-client-provisioner
      containers:
      - name: redis-nfs-client-provisioner
        image: quay.io/external_storage/nfs-client-provisioner:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: nfs-client-root
          mountPath: /persistentvolumes
        env:
        - name: PROVISIONER_NAME
          value: fuseim.pri/ifs
        - name: NFS_SERVER
          value: 192.168.1.1
        - name: NFS_PATH
          value: /data/nfs/redis
      volumes:
      - name: nfs-client-root
        nfs:
          server: 192.168.1.1
          path: /data/nfs/redis
